# Plugin Created by DankOfUK with help from ChatGPT
# Discord for Support: http://discord.gg/2xYgHUfubM

#
#----------------------------------------------------------------
# Part 1 - Discord Related
#----------------------------------------------------------------
#

#----------------------------------------------------------------
# Discord Bot Configuration
#----------------------------------------------------------------
bot:
  enabled: false
  discord_token: "bot-token-here"
  adminRoleID: "ADMIN_ROLE_ID"
  discord_activity: "with KushStaffUtils"
  # Activity Types
  # WATCHING, PLAYING, STREAMING, LISTENING, COMPETING
  discord_activity_type: "STREAMING"

#----------------------------------------------------------------
# Server Shutdown/Startup Logger Configuration  - Discord Bot Required
#----------------------------------------------------------------
serverstatus:
  enabled: true
  channelId: "1146844174524612638"

#----------------------------------------------------------------
# Enable this if you want it to log commands to a file per use! (STORED VIA UUIDS)
#----------------------------------------------------------------
per-user-logging:
  enabled: true # this logs in KushStaffLogger/logs

#----------------------------------------------------------------
# Command Logger Configuration - Discord Bot Required
#----------------------------------------------------------------
# Placeholders for Command Logger
# %player% - Player Name
# %command% - Command it will log
# %server% - pulls from the config option "server_name"
# %time% - Place holder for how many Seconds/Mins/Hours/Days command was ago
commandlogger:
  server_name: "KushStaffUtils"
  logAsEmbed: true
  channel_id: "1146844174524612638"
  message_formats:
    - "\n:information_source: __**Player:**__\n> `%player%`\n \n:gear: __**Use Commands:**__\n> `%command%`\n \n:satellite: __**Server:**__\n> `%server%`\n \n:timer: __**Time:**__\n> %time%"
  embed_title_formats:
    - ":information_source: COMMAND LOGGER"
  # Commands the plugin will ingore
  ignored_commands:
    - "/pin"
    - "/register"
    - "/login"
    - "/password"

  # If false it will log all commands (ignored_commands wont ever be logged)
  # If true it will only log the command in the whitelist_commands (ignored_commands wont ever be logged)
  whitelist_enabled: true
  # Commands the will be logged if set to true (ignored_commands wont ever be logged)
  whitelisted_commands:
    - "/kick"
    - "/ipmute"
    - "/ipban"
    - "/ban"
    - "/tempban"
    - "/mute"
    - "/tempmute"
    - "/warn"
    - "/clearchat"
    - "/gmc"
    - "/gmsp"
    - "/co i"
    - "/co rollback"
    - "/co"
    - "/irp restore"
    - "/irp"
    - "/invsee"
    - "/kill"

#----------------------------------------------------------------
# Suggestion Command Configuration - Discord Bot Required
#----------------------------------------------------------------
# Placeholders for Suggestions Command
# %player% - %player_uuid% - Player Name/Player UUID
# %suggestion% - Suggestion raw text
suggestion:
  enabled: true
  cooldown: 60
  title: "New Suggestion from %player% adwawd"
  description: "%suggestion%"
  color: "#94157f"
  footer: "Submitted by %player% (%player_uuid%)"
  thumbnailUrl: "https://cdn.discordapp.com/avatars/265918857112322052/b047522734170c4d476370f8610b8318.png?size=4096"
  channelId: "1146844174524612638"
  usageMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &cUsage: /suggest <suggestion>"
  sentMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &aYour suggestion (%suggestion%) has been sent!"
  noPermissionMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &cYou do not have permission to use this command."

#----------------------------------------------------------------
# Discord Chat 2 Game Chat Configuration - Discord Bot Required
#----------------------------------------------------------------
# Placeholders for Discord Chat 2 Game Chat
# %author% - Discord User Name
# %message% - Message from discord
discord2game:
  enabled: true
  roleIdRequired: false #If true will require the roleId to use
  roleId: "ROLE_ID_HERE" #This is if roleIdRequired is true
  channelId: "CHANNEL_ID_HERE"
  message: "&9[Discord] &c%author%: &7%message%"

#----------------------------------------------------------------
# Online Players Configuration - Discord Bot Required
#----------------------------------------------------------------
# Placeholders for Online Players Command
# %time% - %player_uuid% - Time when command was used
# %online% - %player_uuid% - List the online players
online_players:
  requireAdminRole: false
  noPlayersTitle: "`Online Players"
  title: "Players Online `(%online%)` - %time%"
  footer: "Server IP: play.example.com"
  thumbnailUrl: "https://cdn.discordapp.com/avatars/265918857112322052/b047522734170c4d476370f8610b8318.png?size=1024"

#----------------------------------------------------------------
# Bug Report Command Configuration - Discord Bot Required
#----------------------------------------------------------------
# Placeholders for Bug Report Command
# %player% - Player Name
# %bug% - Bug message
# %time% - gets how long ago it was - message option
bug_report:
  enabled: true # Set this to true to enable the /strike command
  cooldown: 60 # Cooldown time in seconds
  channelId: "1152384665085296681"
  embed_title: "`A New Bug Report!`"
  message: ":information_source: `Bug Reporter:`\n> **%player%**\n \n:red_circle: `Bug Info:`\n> **%bug%**\n \n:alarm_clock: `When:`\n> %time%"
  noPermissionMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &fYou do not have permission to use this command."
  usageMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &c/bug <report>"
  responseMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &fYour bug report has been logged.\n&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &fOverview: &c%reason%"

#----------------------------------------------------------------
# Player Reporting Command Configuration - Discord Not Required
#----------------------------------------------------------------
# Placeholders for Strike Command
# %player% - Player Name
# %reported_player% - Player who was reported
# %reason% - Reason they reported
# %time% - gets how long ago it was - message option
report:
  enabled: true  # Set this to true to enable the /report command
  channelId: "1152384665085296681"
  embed_title: "`A New Player Report!`"
  message: ":information_source: `Player Reporting:`\n> **%player%**\n \n:red_circle: `Player Reported:`\n> **%reported_player%**\n \n:books: `Reason:`\n> %reason%\n \n:alarm_clock: `When:`\n> %time%"
  cooldown: 60  # Cooldown in seconds
  sentMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &aYour report has been sent!"
  noPermissionMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &cYou do not have permission to use this command."
  usageMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &cUsage: /report <player> <reason>"

#
#----------------------------------------------------------------
# Part 2 - Not Discord Related
#----------------------------------------------------------------
#

#----------------------------------------------------------------
# Chat Logger Configuration - Discord Bot Not Required
#----------------------------------------------------------------
# Placeholders for Chat Logger
# PlaceholderAPI placeholders work also! (must have the plugin installed)
# %player% - Player Name - message/username option
# %message% - Message from in-game - message option
# %player_name% - Player Name - message/username option
# %time% - gets how long ago it was - message option
chatwebhook:
  enabled: true
  webhookUrl: "your-webhook-here"
  username: "%player_name% - Chat Log"
  message: "%time% __**[Global Chat]**__ `%player_name%`**:** *%message%*"

#----------------------------------------------------------------
# Strike Command Configuration - Discord Bot Not Required
#----------------------------------------------------------------
# Placeholders for Strike Command
# %group% - The faction/island name
# %amount% - Amount of strikes
# %reason% - Reason for strikes
# %staff% - Staff/User who gave the strike
strike:
  enabled: false
  webhookUrl: "YOUR_WEBHOOK_URL"
  username: "FactionStrikeBot"
  avatarUrl: "https://cdn.discordapp.com/avatars/689960485495373824/19e1d85814a1a19c84e7ef0e261455a8.png?size=4096"
  embedTitle: ":book: `Faction Strike`"
  embedColor: "#00FF00"
  message: ":information_source: `Faction:`\n> **%group%**\n \n:red_circle: `Amount of Strikes:`\n> **%amount%**\n \n:books: `Reason:`\n> %reason%\n \n:man_beard: `Striked by:`\n> %staff%"
  thumbnail: "https://cdn.discordapp.com/avatars/689960485495373824/19e1d85814a1a19c84e7ef0e261455a8.png?size=4096"
  staffMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &aYou have given &c%group% %amount% &aof strikes for &c%reason%"
  sendCommand: #Here is where you can add "f strikes add %group% %amount%" can also add %reason% if your plugin allows a reason
    - "f strikes add %group% %amount%"
  noPermissionMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &cYou do not have permission to use this command."
  usageMessage: "&c[&c&ᴋᴜѕʜѕᴛᴀꜰꜰᴜᴛɪʟѕ&c] &8» &cUsage: /strike <group> <amount> <reason>"

#----------------------------------------------------------------
# Player Join/Leave Logger Configuration - Discord Bot Not Required
#----------------------------------------------------------------
# Placeholders for Join/Leave Logger
# PlaceholderAPI placeholders work also! (must have the plugin installed)
# %player% - Player Name
player_leave_join_logger:
  enabled: false  # Set this to true to enable player join/leave logging
  #----------------------------
  # Join Message Configuration
  #----------------------------
  joinWebhookUrl: "YOUR_WEBHOOK_URL"
  joinMessage:
    - "> <:dot:1071609577122041856> `%player%` has *joined* the server!"
    - "> <:dot:1071609577122041856> There are now `%server_online%` players online."
    - ""
    - "> :satellite: Server IP > play.servername.net"
    - "> :computer: Website > www.servername.net"
    - "> :department_store: Store > store.servername.net"
  #-----------------------------
  # Leave Message Configuration
  #-----------------------------
  leaveWebhookUrl: "YOUR_WEBHOOK_URL"
  leaveMessage:
    - "> <:dot:1071609577122041856> `%player%` has *left* the server!"
    - "> <:dot:1071609577122041856> There are now `%server_online%` players online."
    - ""
    - "> :satellite: Server IP > play.servername.net"
    - "> :computer: Website > www.servername.net"
    - "> :department_store: Store > store.servername.net"
  #----------------------------------------------------------------
  # Message Embed Configuration - true = embeded message, false = normal message
  #----------------------------------------------------------------
  useEmbed: true  # Set this to true to use Discord embeds

#----------------------------------------------------------------
# Factions Top Announcer Configuration - Discord Bot Not Required
#----------------------------------------------------------------
# Placeholders for Factions Top Announcer
# PlaceholderAPI placeholders work also! (must have the plugin installed)
# This has no default placeholders, use PlaceholderAPI for placeholders.
announcer:
  enabled: false
  webhookUrl: "YOUR_WEBHOOK_URL"
  messages:
    - "awdawdawd"
    - "Factions Top #1: %factionstop_ftop1% - `$%factionstop_ftop1-totalworth%`"
    - "Factions Top #2: %factionstop_ftop2% - `$%factionstop_ftop2-totalworth%`"
    - "Factions Top #3: %factionstop_ftop3% - `$%factionstop_ftop3-totalworth%`"
    - "Factions Top #4: %factionstop_ftop4% - `$%factionstop_ftop4-totalworth%`"
    - "Factions Top #5: %factionstop_ftop5% - `$%factionstop_ftop5-totalworth%`"
    - "Factions Top #6: %factionstop_ftop6% - `$%factionstop_ftop6-totalworth%`"
    - "Factions Top #7: %factionstop_ftop7% - `$%factionstop_ftop7-totalworth%`"
    - "Factions Top #8: %factionstop_ftop8% - `$%factionstop_ftop8-totalworth%`"
    - "Factions Top #9: %factionstop_ftop9% - `$%factionstop_ftop9-totalworth%`"
    - "Factions Top #10: %factionstop_ftop10% - `$%factionstop_ftop10-totalworth%`"
    - ""
    - "Join our server to compete!"
  sendInterval: 60
  embedColor: "#00FF00"
  title: "Factions Top Announcement - testerrr"
  username: "FactionsBot"
  footer: "Factions Top Logger"
  thumbnailUrl: "https://cdn.discordapp.com/avatars/1093413225338507344/a60fa5f0a630cafb471effcf3a3e1bd8.png?size=4096"
  avatarUrl: "https://cdn.discordapp.com/avatars/1093413225338507344/a60fa5f0a630cafb471effcf3a3e1bd8.png?size=4096"

#----------------------------------------------------------------
# Creative Logging Configuration - Discord Bot Not Required
#----------------------------------------------------------------
# Placeholders for Factions Top Announcer
# %player% - Player Name
# %item% - Item ID/Name
# %name% - Item Name (Custom Name)
# %amount% - Item Amount
# %lore% - Item Lore (If they have one)
# %world% - World Name
# %location-x%/%location-y%/%location-z% - Location
creative-logging:
  enabled: true
  webhook-url: "webhook-url-here"
  creative:
    title: "Item has been `Middle Clicked/Moved`"
    player: "%player%"
    item: "%item%"
    amount: "%amount%"
    name: "%name%"
    lore: "%lore%"
    world: "%world%"
    location: "`X:` %location-x% `Y:` %location-y% `Z:` %location-z%"
  drop:
    title: "Item has been `Dropped`"
    player: "%player%"
    item: "%item%"
    amount: "%amount%"
    name: "%name%"
    lore: "%lore%"
    world: "%world%"
    location: "`X:` %location-x% `Y:` %location-y% `Z:` %location-z%"
    enchants: "%enchants%"
